spring.application.name=salon-booking

spring.datasource.url=jdbc:mysql://localhost:3306/salon_booking
spring.datasource.username=root
spring.datasource.password=Shaikh@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true